### ISSUE TITLE
Freezes windows 10 on startup and maybe even more

### ISSUE THREAD

**Issue by lesjj** [juv/vibranceGUI#75] opened 2018-10-15 09:21 UTC
Hey, 

Since a couple of weeks I'm having troubles in Windows 10 and Rainbow Six Siege. I'm already searching for a solution for a long time now and I discovered that at least Vibrancegui (2.3.1.0) is causing me windows 10 freezes (first freeze is on startup windows + vibrancegui on startup). Maybe it even gives me spikes in Rainbow Six Siege, I need to test this further out. Is this a well known bug or? 

Also everything freezes when I alt-tab out of a game, never had this before. So for instance my stream is also freezing for a few seconds, so bad experience for the viewers.. 

Hope to hear from you!

**Comment by juvlarN** [comment] 2018-10-15 17:12
Can you try the beta? http://vibrancegui.com/vibrance/beta 
Btw, I'm not sure if the lag spikes you see are caused by vibranceGUI. The program itself is barely using any resources - you should notice the program running under any circumstances. VibranceGUI itself is just controlling your NVIDIA or AMD driver to add a post-processing effect to each displayed frame which your GPU offers. So vibranceGUI does no heavy lifting of reprocessing every frame or the like. All it does it to tell your driver "from now on, use 100% (or 300% or whatever) digital vibrance/saturation" when you tab into the process you added to the program. The rest is up to the GPU.

**Comment by lesjj** [comment] 2018-10-15 18:12
Hey,

But this is the same version as I already had? It also affects the alt-tabbing speed of games and freezing everything.

Met vriendelijke groet,

Lesley Hermsen

________________________________
Van: juvlarN <notifications@github.com>
Verzonden: Monday, October 15, 2018 7:12:58 PM
Aan: juvlarN/vibranceGUI
CC: lesjj; Author
Onderwerp: Re: [juvlarN/vibranceGUI] Freezes windows 10 on startup and maybe even more (#75)


Can you try the beta? http://vibrancegui.com/vibrance/beta
Btw, I'm not sure if the lag spikes you see are caused by vibranceGUI. The program itself is barely using any resources - you should notice the program running under any circumstances. VibranceGUI itself is just controlling your NVIDIA or AMD driver to add a post-processing effect to each displayed frame which your GPU offers. So vibranceGUI does no heavy lifting of reprocessing every frame or the like. All it does it to tell your driver "from now on, use 100% (or 300% or whatever) digital vibrance/saturation" when you tab into the process you added to the program. The rest is up to the GPU.

**Comment by juvlarN** [comment] 2018-10-15 18:13
Does this also happen when you have the default value for in-game/windows vibrance set? For example 50% for nvidia and 100% for amd?

**Comment by AaronmHardy** [comment] 2018-10-18 15:09
What version/build of windows are you running?  I'm having trouble with some other applications running on Win10 Pro 1803 and 1809.

**Comment by moltam99** [comment] 2018-10-29 22:40
Hello,

For me, starting VibranceGUI (2.3.0.3) causes massive lagspikes for about 5 seconds (mouse cursor teleporting).
I'm on Win 1809.
Happens when started manually, and in autostart as well.

Will try to update VibranceGUI and set different vibrance levels (Win 100, CS:GO 200, 18.10.1 Radeon SW), this is just to let you know that this happens to others aswell.

**Comment by juvlarN** [comment] 2018-12-10 19:23
Any updates on this issue? Windows has been revoking a few of their updates recently, so it might be that Windows is the root cause of this problem. Can anyone pinpoint it down to vibranceGUI? If so, please let me know how to reproduce.

**Comment by juv** [comment] 2019-01-07 19:51
> Any updates on this issue? Windows has been revoking a few of their updates recently, so it might be that Windows is the root cause of this problem. Can anyone pinpoint it down to vibranceGUI? If so, please let me know how to reproduce.

Bump

**Comment by moltam99** [comment] 2019-01-07 20:31
Sorry might have worded it wrong, alt tabbing is very slow in cs:go WITHOUT vibrance gui (i use 4:3 stretched, it is a known limitation), so I can't tell if VibranceGUI is making it any slower.

**Comment by juv** [comment] 2024-12-07 14:36
This issue is old and the problem itself might be fixed in the more recent versions. Please do not hesitate to create a new issue in case this is still reproducible in the newest version.

**Closed by juv** 2024-12-07 14:36 UTC
