### ISSUE TITLE
vibranceGUI suggestion

### ISSUE THREAD

**Issue by kaimian** [juv/vibranceGUI#103] opened 2021-04-05 03:25 UTC
Hello, i didn't find any suggestions page. So i'm using this to give you one. I'm sorry if i am being rude, but i think this suggestion is worth it, if not, please ignore or delete this message.
The vibranceGUI fill a very nice gap on tweaking a game the way you like it without messing up with your desktop in general. And today i felt the necessity to further improve a game with Gamma tweaks. If i could also increase the **gamma** when playing CS:GO or Valorant without messing up with my desktop gamma setting, would be amazing.
I hope you find this suggestion as good as i do. Thank you very much for listening.

**Comment by juv** [comment] 2021-07-28 21:22
Hi, thanks for your suggestion. I'm afraid this is a duplicate of https://github.com/juv/vibranceGUI/issues/8 - which still needs a proper implementation

**Closed by juv** 2021-07-28 21:22 UTC
