### ISSUE TITLE
[Feature Request] Add Brightness Slider

### ISSUE THREAD

**Issue by BennyAlex** [juv/vibranceGUI#84] opened 2019-09-13 03:04 UTC
Hey, first of all, thanks for the nice tool.

I would like to see a brightness slider, for each game and desktop, too.

For my desktop, I only use a brightness of 40%, but for games I want it to have it at 50%+.

I think it would be easy too add, because it should use the same API as the vibrance (at least for Nvidia).

Thanks.

**Comment by juv** [comment] 2019-09-13 15:36
Hi, this is a duplicate of https://github.com/juv/vibranceGUI/issues/8

I have recently rechecked if this is possible but the API has not changed since ages and unfortunately this is still a NDA-driver-only option. NVIDIA never contacted me, as stated in the other issue, so I'm afraid we will not be able to see this feature any time soon.

**Closed by juv** 2019-09-13 15:36 UTC

**Comment by BennyAlex** [comment] 2019-09-14 07:05
Oh okay this is really frustrating. I trust you when you say, thats not possible but I really wonder, that you can set Vibrance withhin the API but anything else dont...

And I also hate Nvidia for the control panel, You can set so many stuff for each game, like Anit Alisign and so on but not the Vibrance and Brightness. 

Thanks for your work.

**Comment by mohcow** [comment] 2023-09-09 21:52
Guess i'll necro this real quick.

@juv Has anything changed on that front? https://github.com/incheon-kim/tarkov-settings managed to get it working somhow, Sadly just for tarkov and not as customizable as yours.
