### ISSUE TITLE
Screen Resolution changes after closing CSGO with vibrance on

### ISSUE THREAD

**Issue by horngjun** [juv/vibranceGUI#56] opened 2018-01-05 07:47 UTC
My screen is running 1920x1080 resolution but when i open csgo with vibrance on, after i close cs, the resolution will automatically changes to 1280x720. I need to change it back manually by myself :( any solution for this?

**Comment by jeffreylec** [comment] 2018-01-21 16:26
This seems to be problem for me too.

**Comment by juvlarN** [comment] 2018-01-21 17:04
Can you try the following version of vibranceGUI:
[vibranceGUI-2.3.0.8-resolution-logging.zip](https://github.com/juvlarN/vibranceGUI/files/1649945/vibranceGUI-2.3.0.8-resolution-logging.zip)

It will create a log file ("vibranceGUI_log.txt") in the folder where you run the executable.
The logs that will be created look like this and might give us a better way to pin down this issue. 

`
Log Entry : 17:59:39 Sonntag, 21. Januar 2018
Changing resolution for application Spotify on screen \\.\DISPLAY1 to resolution: 1280 x 720 @ 120 hz (32 bit, Default)
-------------------------------

Log Entry : 17:59:46 Sonntag, 21. Januar 2018
Changing resolution after exiting/tabbing out of application on screen \\.\DISPLAY1 to resolution: 1920 x 1080 @ 144 hz (32 bit, Default)
-------------------------------

Log Entry : 17:59:51 Sonntag, 21. Januar 2018
Changing resolution for application Spotify on screen \\.\DISPLAY1 to resolution: 1280 x 720 @ 120 hz (32 bit, Default)
-------------------------------

Log Entry : 17:59:59 Sonntag, 21. Januar 2018
Changing resolution after exiting/tabbing out of application on screen \\.\DISPLAY1 to resolution: 1920 x 1080 @ 144 hz (32 bit, Default)
-------------------------------`

When you face this issue, check the log file and see if there is something written in the log file at the time and date you faced the issue. And then let me know here. Thanks

**Comment by horngjun** [comment] 2018-02-06 15:05
Thanks, its fixed.



________________________________

**Comment by jeffreylec** [comment] 2018-02-06 15:17
How did it fix?

**Comment by disco0** [comment] 2018-03-15 23:50
Been having a similar issue with sporadic resolution regression occuring when clicking on explorer windows, vibranceGUI, or games assigned to change vibrance (no games are set to change res, btw)—only when VibranceGUI is open. Since I switch between 120/144 often this happens quite a bit, my solution at the moment has been setting my monitor resolution two times via NCP or with Display Changer, which seems to stop it from jumping back to the actual previous settings and instead into a copy of the current settings. 

Will download the logging version, interested to see what it says this has been driving me nuts lol

**Comment by disco0** [comment] 2018-03-16 03:47
Here's the order of actions I did before getting these in the log:
-I cleared all my program settings, set autostart and left 'Affect Primary Monitor only' disabled for now
-Added Quake Champions the program list, set 92% vibrance level in game and didn't enable the Ingame Resolution option
-Opened the game in borderless windowed mode
-Opened VibranceGUI while in game
-Even after closing the game trying to switch resolutions results in the resolution immediately switching back when changing focus off of ConEmu/Nvidia Control Panel (used to change res)
-Continues until closing VibranceGUI

Maybe something was changed in NVAPI?  Either that or I'm missing something about why its regressing my resolution settings back

```
Log Entry : 6:47:42 PM Thursday, March 15, 2018
Changing resolution after exiting/tabbing out of application on screen \\.\DISPLAY1 to resolution: 1536 x 1080 @ 144 hz (32 bit, Stretch)
-------------------------------

Log Entry : 6:58:54 PM Thursday, March 15, 2018
Changing resolution after exiting/tabbing out of application on screen \\.\DISPLAY1 to resolution: 1536 x 1080 @ 144 hz (32 bit, Stretch)
-------------------------------

Log Entry : 7:02:05 PM Thursday, March 15, 2018
Changing resolution after exiting/tabbing out of application on screen \\.\DISPLAY1 to resolution: 1536 x 1080 @ 144 hz (32 bit, Stretch)
-------------------------------

Log Entry : 8:26:49 PM Thursday, March 15, 2018
Changing resolution after exiting/tabbing out of application on screen \\.\DISPLAY1 to resolution: 1536 x 1080 @ 144 hz (32 bit, Stretch)
-------------------------------
```

**Comment by juvlarN** [comment] 2018-04-13 20:12
@disco0  What kind of a resolution is 1536 x 1080? Looks like a custom resolution to me. Have you tried changing this to something "normal"? Not sure if that should matter because the NVIDIA Api is asked for available resolutions on startup of vibranceGUI...
And it is in "Stretch" mode, have you tried changing that to Default as well?

**Comment by juvlarN** [comment] 2018-04-25 19:02
[vibrance.GUI-2.3.1.0.zip](https://github.com/juvlarN/vibranceGUI/files/1948465/vibrance.GUI-2.3.1.0.zip)
Please try this version, there is a checkbox to disable any resolution change. When the checkbox is ticked, it should stop any resolution change from happening.

**Comment by juv** [comment] 2019-01-07 19:42
This is fixed

**Closed by juv** 2019-01-07 19:42 UTC
