### ISSUE TITLE
Changes Gamma using some Win32 API calls

### ISSUE THREAD

**Issue by JPlayer3** [juv/vibranceGUI#125] opened 2023-03-07 07:04 UTC
Many people are praying that Gamma will be added, but there is open source software that has almost the same functionality.
Can we add the functionality with reference to this one?

The software is Tarkov-specific and cannot specify the application, but it seems to work the same.

https://github.com/incheon-kim/tarkov-settings
![1](https://user-images.githubusercontent.com/72402669/223348720-2988f715-f833-4e9c-97e7-5d798f6ab939.png)

**Comment by juv** [comment] 2024-12-07 14:30
Duplicate of https://github.com/juv/vibranceGUI/issues/125

**Closed by juv** 2024-12-07 14:30 UTC
Labels: duplicate
