### ISSUE TITLE
[FEATURE] Gamma control

### ISSUE THREAD

**Issue by scheMeZa** [juv/vibranceGUI#122] opened 2022-08-10 08:35 UTC
Can we get Gamma control per game too?

**Comment by designstorming** [comment] 2023-09-11 12:00
I was just about to post the same question. The effort would be much appreciated, tho'.
![Screenshot 2023-09-11 135823](https://github.com/juv/vibranceGUI/assets/5846106/df5960b1-4fb1-4584-a372-9c988cb8318a)

**Comment by Slickmaxx** [comment] 2024-01-10 10:22
yes! and for each individual color channel

**Comment by jjcodestuff** [comment] 2024-03-07 20:01
I wish this could be added...seems like this is a dead project unfortunately.

**Comment by juv** [comment] 2024-12-20 19:05
This is a duplicate of https://github.com/juv/vibranceGUI/issues/8 

Please also note the new beta build for `2.5.0`, which includes brightness, contrast and gamma as an experimental preview. Let me know how it goes. See this comment here: https://github.com/juv/vibranceGUI/issues/8#issuecomment-2557553228

**Closed by juv** 2024-12-20 19:05 UTC
Labels: enhancement
