### ISSUE TITLE
Add ability to set "Windows Vibrance Level" lower than 50%

### ISSUE THREAD

**Issue by jeriks31** [juv/vibranceGUI#106] opened 2021-07-28 20:56 UTC
I've put my vibrance at 45% in NVIDIA control panel for better color accuracy on my monitor when I'm not playing csgo, but vibrancegui always turns it back up to 50%

**Comment by juv** [comment] 2021-07-28 21:22
Hi, this is a duplicate of https://github.com/juv/vibranceGUI/issues/62

**Closed by juv** 2021-07-28 21:22 UTC
