### ISSUE TITLE
I want to set it below 50%

### ISSUE THREAD

**Issue by G1ll0u** [juv/vibranceGUI#139] opened 2024-11-17 15:27 UTC
Everything is in the title, I want to be able to set vibrance to less than 50% for specific exes.

Because my eyes hate colors and I'm tired of always going to shitty NVidia Control Panel.

Btw, thanks for this piece of software !
And have a nice day.

**Comment by powerswing** [comment] 2024-11-24 19:46
yeah same plz implement, it's a one line change would've done it myself but don't want to recompile plz thanks!

**Comment by juv** [comment] 2024-12-07 13:09
Hi, this is a duplicate of https://github.com/juv/vibranceGUI/issues/62

**Closed by juv** 2024-12-07 13:09 UTC
